name: example-actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  unit-test: # name of job
    runs-on: ubuntu-latest #Configures the job to run on the latest version of an Ubuntu Linux runner.
    steps:
      - uses: actions/checkout@v3 # checkout repository
      - uses: actions/setup-node@v3 # install node
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci #Clean install your package dependencies
      - name: Test
        run: npm run test
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
